version: '2'
services:
  load-balancer:
    build: ./load-balancer
    links:
      - consul
    ports:
      - "80:80"
  database:
    image: tutum/mongodb:latest
    environment:
      - MONGODB_DATABASE=todos
      - MONGODB_USER=admin
      - MONGODB_PASS=admin
      - STORAGE_ENGINE=wiredTiger --smallfiles
      - JOURNALING=no
  consul:
    image: progrium/consul
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:565/udp"
    command: -server -bootstrap -advertise 10.0.2.15
  registrator:
    image: gliderlabs/registrator
    links:
      - consul
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
    command: -ip=10.0.2.15 consul://consul:8500
  node-rest:
    build: ./node-rest
    ports:
      - "8080"
    links:
      - database
    depends_on:
      - database
    environment:
      - DATABASE_NAME=todos
      - DATABASE_USER=admin
      - DATABASE_PASS=admin
      - SERVICE_80_NAME=http
      - SERVICE_NAME=app
      - SERVICE_TAGS=node-rest
    restart: always
  wso2:
    image: isim/wso2apim
    ports:
      - "9443:9443"
      - "9736:9736"
      - "8243:8243"
      - "8280:8280"
      - "10397:10397"
      - "7711:7711"